# Numpy Basics

Sourc: http://cs231n.github.io/python-numpy-tutorial/

### Basic Data Types

- Numbers
- Booleans
- Strings
- Containers
    - List
        - Slicing
    - Dictionary
    - Tuples
    - Functions
    - Classes
    
### Numpy Data Types

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [4]:
a[0] = 5
a

array([5, 2, 3, 4])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b = np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(2, 10, dtype=np.float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [85]:
np.linspace(1., 4., 6)

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

In [83]:
np.arange(2, 3, 0.1)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9])

In [11]:
np.zeros(2)

array([ 0.,  0.])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [25]:
# Create a 2x2 identity matrix
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [26]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [68]:
np.random.random((2,3))

array([[ 0.61495687,  0.38195006,  0.09999489],
       [ 0.67018677,  0.98601788,  0.30333389]])

### Array Indexing

In [34]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
a[:2, 1:3] # exclusive on 2 value or array and 3 value of matrix

array([[2, 3],
       [6, 7]])

In [37]:
a[[0,0],[1,1]]

array([2, 2])

### Array Math

In [44]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [46]:
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [47]:
y

array([[ 5.,  6.],
       [ 7.,  8.]])

In [43]:
np.add(x,y)

array([[  6.,   8.],
       [ 10.,  12.]])

In [49]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [50]:
np.subtract(y,x)

array([[ 4.,  4.],
       [ 4.,  4.]])

In [51]:
np.multiply(x,y)

array([[  5.,  12.],
       [ 21.,  32.]])

In [52]:
np.divide(x,y)

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [53]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [61]:
# Inner product for vectors

x.dot(y)

# Substitute Syntax

np.dot(x, y)

array([[ 19.,  22.],
       [ 43.,  50.]])

In [62]:
x = np.array([[1,2],[3,4]])

In [63]:
np.sum(x)

10

In [64]:
np.sum(x, axis=0)

array([4, 6])

In [65]:
np.sum(x, axis=1)

array([3, 7])

In [66]:
x

array([[1, 2],
       [3, 4]])

In [67]:
x.T

array([[1, 3],
       [2, 4]])

### Matrix Transformation

In [76]:
# Create an empty matrix with the same shape as x (Fix)
w = ([1,2,3], [4,5,6]) 
v = np.empty_like(w)
v

array([[0, 0, 0],
       [0, 0, 0]])

In [78]:
# We will add the vector v to each row of the matrix x
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [79]:
# We will add the vector v to each row of the matrix x
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
y = x + vv
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

### Matrix Creation

In [86]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Numpy Random Modules

In [98]:
np.random.rand(3)

array([ 0.25553371,  0.59601331,  0.87705028])

In [99]:
np.random.rand(3, 3)

array([[ 0.75245378,  0.1031066 ,  0.35585535],
       [ 0.39826007,  0.48132759,  0.19546536],
       [ 0.45698166,  0.71126566,  0.62267946]])

In [108]:
np.random.randn(10)

array([-1.45826402,  0.8538956 ,  0.00674939,  2.22542615, -0.45747553,
       -0.21182838, -0.20427235, -0.41279535, -0.24827488,  0.19818823])

In [114]:
np.random.randint(low=5, high= 10, size=5, dtype=int)

array([5, 5, 9, 5, 9])

In [119]:
np.random.random_sample(size = 5)

array([ 0.73140687,  0.74221643,  0.67312523,  0.66913337,  0.10535325])

In [120]:
np.random.random(size=5)

array([ 0.50559423,  0.05886599,  0.43627051,  0.83306266,  0.76107544])

In [121]:
np.random.ranf(size=5)

array([ 0.86178807,  0.99132356,  0.48616522,  0.83358075,  0.91165592])

In [122]:
np.random.sample(size=5)

array([ 0.83471244,  0.19046287,  0.79872856,  0.41414813,  0.14266293])

In [129]:
x = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(x)

4

In [132]:
np.random.choice(x[size=10])

SyntaxError: invalid syntax (<ipython-input-132-ba1dcdd6bb9c>, line 1)