# Scipy Tutorial

Source: https://docs.scipy.org/doc/scipy/reference/tutorial/general.html#scipy-organization


### Introduction

In [40]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy

In [41]:
from scipy import linalg, optimize

### Basic Functions

In [42]:
import numpy as np
#np.some_function()

In [43]:
#from scipy import some_module()
#some_module.some_function()

### Index Tricks

In [44]:
a = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [45]:
a = np.r_[3,[0]*5, -1:1,10j]
a

array([ 3. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,
       -1. +0.j,  0. +0.j,  0.+10.j])

In [46]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [47]:
np.mgrid[0:5:4j, 0:5:4j]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.66666667,  1.66666667,  1.66666667,  1.66666667],
        [ 3.33333333,  3.33333333,  3.33333333,  3.33333333],
        [ 5.        ,  5.        ,  5.        ,  5.        ]],

       [[ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ]]])

##### Polynomials

In [48]:
from numpy import poly1d
p = poly1d((3,4,5))
print(p)

   2
3 x + 4 x + 5


In [49]:
print(p*p)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [50]:
print(p.integ(k=6)) #integrated

   3     2
1 x + 2 x + 5 x + 6


In [51]:
print(p.deriv()) #differentiated

 
6 x + 4


In [52]:
p([4, 5])

array([ 69, 100])

##### Vectorizing functions

In [53]:
def addsubtract(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [54]:
vec_addsubtract = np.vectorize(addsubtract)

In [55]:
vec_addsubtract([0,3,6,7],[1,3,5,7])

array([ 1,  6,  1, 14])

##### Type Handling

In [56]:
np.cast['f'](np.pi)

array(3.1415927410125732, dtype=float32)

##### Other Useful Functions

In [57]:
x = np.r_[-2:3]
x

array([-2, -1,  0,  1,  2])

In [58]:
np.select([x>3, x>= 0],[0, x+2])

array([0, 0, 2, 3, 4])

### Special Functions
##### Special functions (scipy.special)

In [59]:
from scipy import special
def drumhead_height(n, k, distance, angle, t):
    kth_zero = special.jn_zeros(n, k)[-1]
    return np.cos(t) * np.cos(n*angle) * special.jn(n, distance*kth_zero)

In [60]:
theta = np.r_[0:2*np.pi:50j]
radius = np.r_[0:1:50j]

x = np.array([[r * np.cos(theta) for r in radius]])
y = np.array(([r * np.sin(theta) for r in radius]))
z = np.array([drumhead_height(1, 1, r, theta, 0.5) for r in radius])

In [61]:
# import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D
# from matplotlib import cm
# fig = plt.figure()
# ax = Axes3D(fig)
# ax.plot_surface(x, y, z, rstride=1, cstride=1, cmap=cm.jet)
# ax.set_xlabel('X')
# ax.set_ylabel('Y')
# ax.set_zlabel('Z')
# plt.show()

##### Cython Bindings for Special Functions

In [62]:
# cimport scipy.special.cyphon_special as csc
# cdef:
#     double x = 1
#     double complex z = 1 + 1j
#     double si, ci, rgam
#     double complex cgam
# rgam = csc.gamma(x)
# print(rgam)
# cgam = csc.gamma(z)
# print(cgam)
# csc.sici(x, &si, &ci)
# print(si, ci)

I skipped majority of the cython sections because it is not relavent to me 

##### Functions not in scipy.model

In [63]:
def binary_entropy(x):
    return -(sc.xlogy(x,x) + sc.xlog1py(1, -x, -x))/np.log(2)

In [64]:
def heaviside(x):
    return 0.5*(np.sign(x) + 1)

In [65]:
def step(x):
    return 0.5*(np.sign(x) + np.sign(1 - x))

In [66]:
def ramp(x):
    return np.maximum(0, x)

## Integration

In [67]:
help(scipy.integrate)

Help on package scipy.integrate in scipy:

NAME
    scipy.integrate

DESCRIPTION
    Integration and ODEs (:mod:`scipy.integrate`)
    
    .. currentmodule:: scipy.integrate
    
    Integrating functions, given function object
    
    .. autosummary::
       :toctree: generated/
    
       quad          -- General purpose integration
       dblquad       -- General purpose double integration
       tplquad       -- General purpose triple integration
       nquad         -- General purpose n-dimensional integration
       fixed_quad    -- Integrate func(x) using Gaussian quadrature of order n
       quadrature    -- Integrate with given tolerance using Gaussian quadrature
       romberg       -- Integrate func using Romberg integration
       quad_explain  -- Print information for use of quad
       newton_cotes  -- Weights and error coefficient for Newton-Cotes integration
       IntegrationWarning -- Warning on issues during integration
    
    Integrating functions, given fixed 

##### General Integration

In [70]:
import scipy.integrate as integrate
import scipy.special as special

result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
result

(1.1178179380783253, 7.866317216380692e-09)

In [73]:
from numpy import sqrt, sin, cos, pi
I = sqrt(2/pi)*(18.0/27*sqrt(2)*cos(4.5)
                - 4.0/27*sqrt(2)*sin(4.5) + sqrt(2*pi)
                * special.fresnel(3/sqrt(pi))[0])
I

1.117817938088701

In [75]:
print(abs(result[0]-I))

1.03757002989e-11


In [83]:
# from scipy.integrate import quad
# def integrand(x, a, b):
#     return a*x**2 + b

# a = 2
# b = 1
# I = quad(integrand(0,1,args=(a,b)))
# I

In [85]:
from scipy.integrate import quad
def integrand(t, n, x):
    return np.exp(-x*t) / t**n

In [87]:
def expint(n, x):
    return quad(integrand, 1, np.inf, args=(n,x))[0]

In [89]:
vec_expint = np.vectorize(expint)
vec_expint

In [90]:
vec_expint(3, np.arange(1.0, 4.0, 0.5))

import scipy.special as special
special.expn(3, np.arange(1.0, 4.0, 0.5))

array([ 0.10969197,  0.05673949,  0.03013338,  0.01629537,  0.00893065,
        0.00494538])

In [91]:
result = quad(lambda x: expint(3, x), 0, np.inf)
print (result)

(0.33333333325010883, 2.8604069921197956e-09)


In [92]:
I3 = 1.0/3.0
print(I3)

0.3333333333333333


In [93]:
print(I3 - result[0])

8.322448286079975e-11




##### General Multiple Intergration

In [99]:
from scipy.integrate import quad, dblquad
def I(n):
    return dblquad(lambda t, x: np.exp(-x*t)/t**n, 0, np.inf, lambda x: 1, lambda x: np.inf)


In [101]:
print (I(4))
print (I(3))
print (I(2))

(0.2500000000043577, 1.2983033469368098e-08)
(0.33333333325010883, 1.3888461883425516e-08)
(0.4999999999985751, 1.3894083651858995e-08)


In [104]:
from scipy import integrate
N = 5
def f(t, x):
    return np.exp(-x*t)/t**N

integrate.nquad(f, [[1, np.inf],[0,np.inf]])

(0.2000000000189363, 1.3682975855986131e-08)

In [109]:
from scipy import integrate
def f(x, y):
    return x*y

def bounds_y():
    return [0, 0.5]

def bounds_x(y):
    return [0, 1-2*y]

integrate.nquad(f, [bounds_x, bounds_y])

(0.010416666666666668, 4.101620128472366e-16)

##### Integrating using Sample

In [111]:
import numpy as np
def f1(x):
    return x**2

def f2(x):
    return x**3

x = np.array([1,3,4])
y1 = f1(x)
from scipy.integrate import simps
I1 = simps(y1, x)
print (I1)

21.0


In [112]:
y2 = f2(x)
I2 = integrate.simps(y2, x)
print (I2)

61.5


##### Functions

In [119]:
# import os, ctypes
# from scipy import integrate, LowLevelCallable

# lib = ctypes.CDLL(os.path.abspath('testlib.so'))
# lib.f.restype = ctypes.c_double
# lib.f.argtypes = (ctypes.c_int, ctypes.POINTER(ctypes.c_double), ctypes.c_void_p)

# c = ctypes.c_double(1.0)
# user_data = ctypes.cast(ctypes.pointer(c), ctypes.c_void_p)

# func = LowLevelCallable(lib.f, user_data)

In [121]:
#integrate.nquad(func, [[0, 10], [-10, 0], [-1, 1]])

In [123]:
from scipy.integrate import odeint
from scipy.special import gamma, airy
y1_0 = 1.0/3**(2.0/3.0) / gamma(2.0/3.0)
y0_0 = -1.0/3**(1.0/3.0) / gamma(1.0/3.0)
y0 = [y0_0, y1_0]
def func(y, t):
    return [t*y[1], y[0]]