# Perceptron In Scikit
### Preliminaries

In [25]:
# load the required libraries
import numpy as np

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [26]:
# load the iris dataset
iris = datasets.load_iris()

# create our X and Y data
X = iris.data
y = iris.target

# View the Iris Data

In [27]:
y[:5]

array([0, 0, 0, 0, 0])

In [28]:
# View the first five observations of our x data.
# Notice that there are four independent variables (features)
X[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

### Split The Iris Data Into Training And Test

In [29]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

### Preprocess the X Data By Scaling

In [30]:
# Train the scaler, which standarizes all the features to have mean = 0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

### Train A Perceptron Learner

In [32]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.3\
ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0)

# Train the perceptron
ppn.fit(X_train_std, y_train)

/Users/Kavi/anaconda/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:73: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


Perceptron(alpha=0.0001, class_weight=None, eta0=0.1, fit_intercept=True,
      max_iter=40, n_iter=None, n_jobs=1, penalty=None, random_state=0,
      shuffle=True, tol=None, verbose=0, warm_start=False)

### Apply the Trained Learner to Test Data

In [33]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred= ppn.predict(X_test_std)

### Compare the Predicted Y with The True Y

In [34]:
# View the predicted y test data
y_pred

array([0, 2, 1, 1, 2, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 2,
       1, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0])

In [35]:
# View the true y test data
y_test

array([0, 2, 1, 1, 2, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 2,
       1, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 0])

### Examine Accuracy Metric

In [36]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong/total observations)
print ('Accuracy: %.2f' %accuracy_score(y_test, y_pred))

Accuracy: 0.91


Source: https://chrisalbon.com/deep-learning/perceptron_in_scikit.html