# Generating Random Numbers With Numpy
### Import Numpy

In [1]:
import numpy as np

### Generate A Random Number From The Normal Distribution

In [2]:
np.random.normal()

2.2328387225572217

### Generate Four Random Numbers From The Normal Distribution

In [4]:
np.random.normal(size=4)

array([ 0.40175358,  0.30920477, -0.78277731, -0.73869148])

### Generate Four Random Numbers From The Uniform Distribution

In [5]:
np.random.uniform(size=4)

array([ 0.31237589,  0.09402777,  0.94496015,  0.15489675])

### Generate Four Random Integers Between 1 and 100

In [7]:
np.random.randint(low=1, high=100, size=4)

array([24, 42, 21, 43])

Source: https://chrisalbon.com/python/generating_random_numbers_with_numpy.html