In [8]:
# Example 2-1
symbols = '%^%*^(^&^$$^%$)'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
    
codes

[37, 94, 37, 42, 94, 40, 94, 38, 94, 36, 36, 94, 37, 36, 41]

In [9]:
#Example 2-2
[ord(symbol) for symbol in symbols]

[37, 94, 37, 42, 94, 40, 94, 38, 94, 36, 36, 94, 37, 36, 41]

In [11]:
# Example 2-4
colors = ['black','white']
sizes = ['S','M','L']
[(color, size) for color in colors for size in sizes]

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [12]:
# Example 2-6
for tshirt in ('%s %s' %(c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [15]:
# Example 2-7
traveler_ids = [('USA', '31195855'), ('BRA','CE342567'), ('ESP','XDA2058856')]
for passport in sorted(traveler_ids):
    print('%s/%s', passport)

%s/%s ('BRA', 'CE342567')
%s/%s ('ESP', 'XDA2058856')
%s/%s ('USA', '31195855')


In [17]:
ls = [1,2,3,4]
ls.append(4)
ls

[1, 2, 3, 4, 4]

In [20]:
ls.clear()
ls

[]

In [22]:
ls = [1,2,3,4]
ls.__delitem__(2)
ls

[1, 2, 4]

In [23]:
ls = [1,2,3,4]
ls.extend([98,7293,132])
ls

[1, 2, 3, 4, 98, 7293, 132]

In [24]:
ls.__getitem__(3)

4

In [26]:
# first occurence index value
ls.index(4)

3

In [28]:
ls = [1,2,3,4]
ls.insert(2,89)
ls

[1, 2, 89, 3, 4]

In [29]:
ls.__iter__()

In [30]:
ls.__len__()

5

In [31]:
ls = [1,2,3,4]
ls.__mul__(5)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [32]:
# inclaec *=
ls = [1,2,3,4]
ls.__imul__(5)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [33]:
ls = [1,2,3,4]
ls.__rmul__(5)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [35]:
ls = [1,2,3,4]
ls.pop(2)

3

In [36]:
ls

[1, 2, 4]

In [39]:
# remove first occurance
ls = [1,2,3,4]
ls.remove(3)
ls

[1, 2, 4]

In [41]:
ls = [1,2,3,4]
ls.reverse()
ls

[4, 3, 2, 1]

In [43]:
ls = [1,2,3,4]
ls.__reversed__()

In [44]:
# overwrite existing item
ls = [1,2,3,4]
ls.__setitem__(3,98)
ls

[1, 2, 3, 98]

In [49]:
# Example 2-12:
board = [['_']*3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [50]:
[['_']*3]*3

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [55]:
ls = [1,2,3,4,5,5,6,6,6,6,8,9]
ls.transpose()

AttributeError: 'list' object has no attribute 'transpose'

In [63]:
# Example 2-22
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
a = a.reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

from collection import deque
dq = deque(range(10, maxlen=10)
dq

In [77]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [80]:
dq = deque(range(10), maxlen=10)
dq.rotate(-4)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])